from typing import List, Optional
from notabene.models.base import Source
from notabene.models.pdf import PDFDocument
from notabene.models.web import WebSource
from notabene.models.note import Note

def export_to_markdown(sources: List[Source], output_file: str) -> None:
    """
    Exports a list of sources and their notes to a Markdown file.

    Args:
        sources (List[Source]): List of source objects to export.
        output_file (str): Path to the output Markdown file.
    """
    markdown_content = []

    markdown_content.append("# Exported Notes\n")
    markdown_content.append(f"Generated by NotaBene\n")
    markdown_content.append("---\n")

    for source in sources:
        # Title
        markdown_content.append(f"## {source.title}\n")
        
        # Metadata block
        markdown_content.append("**Metadata**:\n")
        markdown_content.append(f"- **Type**: {source.type.capitalize()}\n")
        
        if source.authors:
            markdown_content.append(f"- **Authors**: {source.authors}\n")
        
        if source.date_added:
            markdown_content.append(f"- **Added**: {source.date_added.strftime('%Y-%m-%d')}\n")

        # Specific fields
        if isinstance(source, PDFDocument):
            if source.year:
                markdown_content.append(f"- **Year**: {source.year}\n")
            if source.journal:
                markdown_content.append(f"- **Journal**: {source.journal}\n")
            if source.doi:
                markdown_content.append(f"- **DOI**: {source.doi}\n")
            if source.file_path:
                markdown_content.append(f"- **File**: `{source.file_path}`\n")
            if source.abstract:
                markdown_content.append(f"\n**Abstract**:\n> {source.abstract}\n")

        elif isinstance(source, WebSource):
            if source.url:
                markdown_content.append(f"- **URL**: [{source.url}]({source.url})\n")
            if source.domain:
                markdown_content.append(f"- **Domain**: {source.domain}\n")
            if source.date_published:
                markdown_content.append(f"- **Published**: {source.date_published.strftime('%Y-%m-%d')}\n")
            if source.date_accessed:
                markdown_content.append(f"- **Accessed**: {source.date_accessed.strftime('%Y-%m-%d')}\n")

        # Tags
        if source.tags:
             tags_str = ", ".join([tag.name for tag in source.tags])
             markdown_content.append(f"- **Tags**: {tags_str}\n")

        # Notes
        if source.notes:
            markdown_content.append(f"\n### Notes\n")
            for note in source.notes:
                icon = "📝"
                if note.note_type.name == "IDEA":
                    icon = "💡"
                elif note.note_type.name == "QUESTION":
                    icon = "❓"
                elif note.note_type.name == "ARGUMENT":
                    icon = "🗣️"
                elif note.note_type.name == "QUOTE":
                    icon = "❝"
                
                markdown_content.append(f"#### {icon} {note.note_type.name.capitalize()}\n")
                markdown_content.append(f"{note.content}\n")
                if note.date_created:
                     markdown_content.append(f"*{note.date_created.strftime('%Y-%m-%d %H:%M')}*\n")
                markdown_content.append("\n")

        markdown_content.append("---\n")

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("".join(markdown_content))
